# -*- coding: utf-8 -*-
"""Assignment 1a.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14qleOgSTzA0r3xCQ1syUUNPPzqnLujQS

1.
"""

print('Twinkle, twinkle, little star,\n\tHow I wonder what you are!\n\t\tUp above the world so high,\n\t\tLike a diamond in the sky.')
print('Twinkle, twinkle, little star,\n\tHow I wonder what you are')

"""2."""

color_list = ['Red','Green','White', 'Black']
print(color_list[0])
print(color_list[-1])

"""3."""

n = input('Enter integer:')
a = int(n)
b = int(n+n+n+n)
c = int(n+n+n+n+n+n+n)
print('n+nnnn+nnnnnnn =', a+b+c)

"""4."""

import math
r = float(input('Enter radius:'))
vol_sph = (4/3)*math.pi*(r**3)
print('The volume of the sphere is: ', round(vol_sph,3))

"""5."""

n = float(input('Enter number: '))
if abs(17-n) > 17:
  print('Double the absolute difference is:', round(2*abs(17-n),2))
else:
  print('Differnce is: ', n-17)

"""6."""

import math

x1 = float(input('Enter point x1: '))
x2 = float(input('Enter point x2: '))
y1 = float(input('Enter point y1: '))
y2 = float(input('Enter point y2: '))

d = math.sqrt((x2-x1)**2 + (y2-y1)**2)
print('The distance between the two points is: ',round(d,2))

"""7."""

x = 23
y = 45
print(str(x)+'+'+str(y)+'='+str(x+y))