# -*- coding: utf-8 -*-
"""Assignment 1b.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VpGoaXMY8xGh9iGJdYM8Hh7e1Sctr2n1

Loops and Conditionals

1.
"""

fib=0
fib1=1
print(fib)
print(fib1)
while fib < 50 and fib1 < 50:
  fib=fib+fib1
  fib1=fib+fib1
  if fib < 50 and fib1 < 50:
    print(fib)
    print(fib1)

"""2."""

A = int(input('Enter number: '))
B = int(input('Enter number: '))
C = int(input('Enter number: '))
D = int(input('Enter number: '))
if A == B == C == D:
  print(4*(A+B+C+D))
else:
  print(A+B+C+D)

"""3."""

month = input('Enter birth month: ')
date = int(input('Enter birth date (1-31): ')) - 1
if (month.lower() == 'january' and date in range(20,31)) or (month.lower() == 'february' and date in range(1,18)):
  print('Astrological Sign: Aquarius')
elif (month.lower() == 'february' and date in range(19,29)) or (month.lower() == 'march' and date in range(1,20)):
  print('Astrological Sign: Pisces')
elif (month.lower() == 'march' and date in range(21,31)) or (month.lower() == 'april' and date in range(1,19)):
  print('Astrological Sign: Aries')
elif (month.lower() == 'april' and date in range(20,30)) or (month.lower() == 'may' and date in range(1,20)):
  print('Astrological Sign: Taurus')
elif (month.lower() == 'may' and date in range(21,31)) or (month.lower() == 'june' and date in range(1,20)):
  print('Astrological Sign: Gemini')
elif (month.lower() == 'june' and date in range(21,30)) or (month.lower() =='july' and date in range(1,22)):
  print('Astrological Sign: Cancer')
elif (month.lower() == 'july' and date in range(23,31)) or (month.lower() == 'august' and date in range(1,22)):
  print('Astrological Sign: Leo')
elif (month.lower() == 'august' and date in range(23,31)) or (month.lower() == 'september' and date in range(1,22)):
  print('Astrological Sign: Virgo')
elif (month.lower() == 'september' and date in range(23,30)) or (month.lower() == 'october' and date in range(1,22)):
  print('Astrological Sign: Libra')
elif (month.lower() == 'october' and date in range(23,31)) or (month.lower() == 'november' and date in range(1,21)):
  print('Astrological Sign: Scorpio')
elif (month.lower() == 'november' and date in range(22,30)) or (month.lower() == 'december' and date in range(1,21)):
  print('Astrological Sign: Sagittarius')
elif (month.lower() == 'december' and date in range(22,31)) or (month.lower() == 'january' and date in range(1,19)):
  print('Astrological Sign: Capricorn')
else:
  print('Not a valid date')

"""4."""

print('      ***')
print('     *   *')
print('    *     *')
print('   *********')
print('  *         *')
print(' *           *')
print('*             *')

for i in range(7):
  if i == 0:
    print('***')
  elif i == 3:
    print('*****')
  else:
     print('*  *')

"""Lists

1.
"""

subjects=["Maths","science","physics"]
colors=["red","yellow","green","black"]
fruits=["apple","banana","orange","kiwi","Mango"] 
numbers=["1","2","3","4","5","6"]
output=subjects[1],colors[2],fruits[3],numbers[4]
list(output)

"""2."""

fruits=["apple","banana","orange","kiwi","Mango"] 
fruits.append('berry')
print(fruits)

"""3."""

output=[]
for i in range(1,11):
  output.append(str(i**2))
output

"""4."""

list1=['red','orange','yellow']
list2=['strawberry','orange','banana']
for i in range(len(list1)):
  if list1[i]==list2[i]:
    print('Common Member!')
    print('Common member is:',list1[i])

"""5."""

values=[1,2,3,4,5]
print('Maximum value is:', max(values))
print('Minimum value is:', min(values))